/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:1c5d79b8-53b1-4b4b-ab2f-5bec75b0779a",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_eWXiD8iVi",
    "aws_user_pools_web_client_id": "1ckl4lddb1opcqsgd07qn70otk",
    "oauth": {}
};


export default awsmobile;
